//set up request - requests html from other pages on the web
var request = require('request');

//set up express
var express = require('express');
var app = express();//maybe need to move this lower below other requires?
//set up express//

//require the routes
var violations = require('./routes/violations');
var rats = require('./routes/rats');


//logs requests for 'middleware' for node.js
var logger = require('morgan');
app.use(logger('dev'));
//logs requests for 'middleware' for node.js//


//no idea what this does - from Jason's class solution:
//somehow links to the public director that has static html files (created by a person, not generated by server)??? sets index.html?
app.use( express.static('public') );

//set up above route violations - connects to violations.js in the routes directory
app.use('/violations', violations);
app.use('/rats', rats);

//set up ejs
app.set('views', './views');
app.set('view engine', 'ejs');
//set up ejs //

//set up server
var port = 3000;
var server = app.listen(port, function (){
  //this console.log will appear in node, when the server has started
  console.log ("server started! on port", port);
});
//set up server //
